/**
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.sctest.scdsl.tests.SCDslInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(SCDslInjectorProvider.class)
@SuppressWarnings("all")
public class SCDslParsingTest {
  @Inject
  private /* ParseHelper<Domainmodel> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field SCDslParsingTest.parseHelper refers to the missing type Domainmodel"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
