/*
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.sctest.scdsl.services.SCDslGrammarAccess;

@SuppressWarnings("all")
public class SCDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SCDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Condition_PostConditionParserRuleCall_0_1_or_PreConditionParserRuleCall_0_0;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SCDslGrammarAccess) access;
		match_Condition_PostConditionParserRuleCall_0_1_or_PreConditionParserRuleCall_0_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getConditionAccess().getPostConditionParserRuleCall_0_1()), new TokenAlias(false, false, grammarAccess.getConditionAccess().getPreConditionParserRuleCall_0_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getPostConditionRule())
			return getPostConditionToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getPreConditionRule())
			return getPreConditionToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * PostCondition:
	 * 	'PostCondition'
	 * ;
	 */
	protected String getPostConditionToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "PostCondition";
	}
	
	/**
	 * PreCondition:
	 * 	'PreCondition'
	 * ;
	 */
	protected String getPreConditionToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "PreCondition";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Condition_PostConditionParserRuleCall_0_1_or_PreConditionParserRuleCall_0_0.equals(syntax))
				emit_Condition_PostConditionParserRuleCall_0_1_or_PreConditionParserRuleCall_0_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     PreCondition | PostCondition
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '{' 'Name' ':' name=ID
	 */
	protected void emit_Condition_PostConditionParserRuleCall_0_1_or_PreConditionParserRuleCall_0_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
